import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = { title: "Privacy", description: "How RepArc handles account and training data." };

export default function PrivacyPage() {
  return (
    <LegalPage eyebrow="Privacy · 7 September 2026" title="Your data stays yours." summary="This notice explains the data needed for your training and the separate, optional choice to help improve RepArc.">
      <section><h2>What RepArc stores</h2><p>RepArc stores your verified email and internal account ID; the training label you choose; profile preferences such as units, program track, lifting experience, bodyweight and goals; workout entries, swaps, readiness selections, training maxes and weigh-ins; and any feedback you submit. Minimal crash diagnostics are collected only when you opt in. Short-lived security counters record the account ID, protected action, request count and timing—but never workout contents or network addresses—to control abuse.</p></section>
      <section><h2>Why it is used</h2><p>The data is used to authenticate you, generate and adjust training views, preserve history, synchronize devices, restore backups, investigate feedback and keep the service reliable. RepArc does not sell personal data, use it for advertising, or store payment information.</p></section>
      <section><h2>Exercise familiarity and recovery</h2><p>Workout records also store the suggested load when one exists, rep and effort targets, reduced set prescription, familiarity state and your recovery responses. These remain with your training history and are included in JSON backups. They help explain recommendations and track your own response; they are not included in the separate 30-day crash diagnostics or sent to an external analytics service. RepArc does not claim these records independently validate its program.</p></section>
      <section><h2>Optional improvement participation</h2><p>Sharing is off by default. A separate choice allows RepArc maintainers to evaluate future recommendations using exercise identity, program track, lifting experience, prescribed load/reps/effort/sets, completed values, readiness and recovery responses. This copy is stored separately in Supabase, linked to your internal account ID, without your email, name or free-text notes. It is pseudonymous, not anonymous. We do not collect earlier sessions into this dataset when you opt in. Declining leaves your workout features available. We do not sell these records, use them for advertising, send them to external analytics services or automatically train/change the production algorithm.</p></section>
      <section><h2>Improvement-data control and access</h2><p>Participation lasts up to one year and then requires a new opt-in. Raw improvement records are deleted after 180 days from first collection; updates do not extend retention. Consent, withdrawal and access records expire after 365 days. Authorized RepArc maintainers may use a restricted, audited evaluation export; no other app user may access your records. Under Setup → Account &amp; privacy you can export your evaluation records or withdraw. Confirmed withdrawal immediately stops collection and deletes the identifiable evaluation copy while keeping your ordinary workout history. If offline, reconnect to submit withdrawal; the app confirms when it is saved. Account deletion also removes improvement records and their audit history. No anonymous public aggregates are currently produced.</p></section>
      <section><h2>History archives and sync conflicts</h2><p>Larger training histories are split into verified, account-owned cloud chunks. Reports and JSON exports include the complete history up to the documented account limits. Replaced or abandoned chunks are removed after a two-day cleanup window. If devices edit the same item concurrently, the confirmed cloud value is kept and a device-local conflict copy is retained for your review. Export that copy under Restore backup; it is removed with account deletion on that device.</p></section>
      <section><h2>Offline and cloud copies</h2><p>Your latest training copy and unfinished workout drafts can be stored in this browser&apos;s IndexedDB and local storage so training continues without a connection. Authentication credentials use protected cookies. Cloud account and training records are processed by Supabase; the web app is hosted by Netlify; authentication email is delivered through the configured mail provider.</p></section>
      <section><h2>Retention and control</h2><p>Training data remains until you change or delete it. Submitted feedback is automatically deleted after 180 days, opt-in diagnostics after 30 days, and inactive security counters after 2 days. Account deletion removes the account and its live cloud training profile, feedback, diagnostics and counters immediately, plus that account&apos;s offline copy on the current device. Provider backups may retain encrypted copies until their normal backup cycle expires. You can export CSV and JSON copies from Data &amp; account before deletion.</p></section>
      <section><h2>Shared devices and backups</h2><p>Signing out removes the protected session but intentionally preserves that account&apos;s isolated offline training copy for the next sign-in. Use Delete account when you want the current-device copy erased too. Files you export are outside RepArc&apos;s control, so protect or delete them yourself.</p></section>
      <section><h2>Questions or requests</h2><p>Use the private feedback form in Data &amp; account or email <a href="mailto:reparcapp@gmail.com">reparcapp@gmail.com</a> for privacy questions. If you can sign in, the deletion control is the fastest way to exercise deletion rights. Do not include medical or highly sensitive information in feedback.</p></section>
    </LegalPage>
  );
}
